### ISSUE TITLE
Multiple semesters

### ISSUE THREAD

**Issue by clentner** [ajgajg1134/RITFoodDataAnalysis#16]
The linear regression is thrown off when there are multiple semesters in the csv file. Every transaction that increases debit amount should be treated as the start of a new line of best fit.

![untitled](https://cloud.githubusercontent.com/assets/9728483/5959999/6e47c92a-a7a0-11e4-9209-d3f7b1d42c0a.png)

**Comment by ajgajg1134** [comment]
This issue has been mostly fixed with commit 03c01f unfortunately some of this issue continues to exist as a problem with the way RIT exports data that contains rollover amounts. (See issue #13)
